---

- hosts: all # apply to all hosts
  become: true # sudo 
  tasks:

  - name: update repo index
    apt:
      update_cache: yes

  - name: uninstall apache2 package # desc of what the play does
    apt: # module
      name: apache2 # the package to remove with apt
      state: absent # remove the package

  - name: uninstall php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
